### ISSUE TITLE
Endless Self Execution

### ISSUE THREAD

**Issue by vedadux** [aniemetz/ddSMT#1]
Your delta debuger helped me a lot in finding a very nasty and elusive bug today, so i thought I should share some strange behaviour I have noticed while trying to use it. I have cloned the project today in order to delta debug the z3 based SMT solver I am currently working on. However, when I tried running the python script ddsmt.py out of the box, it did not work at all and seemed to be stuck in an endless loop. The value of `g_args.optimize` seems to always be `True` and trigger the conditional `if g_args.optimize:` which then goes into an endless self loading loop. Adding `g_args.optimize = False` in front of that if statement fixed it for me and ddSMT seemed to work as expected after that. 
This is how I called ddsmt.py:
`python3.6 ddsmt.py -o inf.smt2 outf.smt2 solve.sh`
In my case `solve.sh` is just a bash script which returns -1 when z3 and my solver produce a different output and 0 otherwise.

**Comment by aniemetz** [comment]
@vedadux thanks for reporting! And sorry for taking so long to respond, I somehow forgot to enable notifications for issues :(  https://github.com/aniemetz/ddSMT/commit/b3d97ddcad62c924424ef02727a9e607c43d2b8c fixes this issue!
