### ISSUE TITLE
Extend ddSMT to support (get-model) command

### ISSUE THREAD

**Issue by blishko** [aniemetz/ddSMT#16]
I found it very useful to use ddSMT to minimize the input SMT-LIB2 script when my solver was producing invalid model.
However, the current version does not recognize (get-model) command, so I had to add the support myself.

Would you consider adding support for this command? I have my own solution which I could submit as a pull request if needed.

**Comment by aniemetz** [comment]
I'd be happy if you submit a PR!

**Comment by blishko** [comment]
Resolved in #18 

Thanks again for developing this tool!
